### ISSUE TITLE
MMSP is GPLv3

### ISSUE THREAD

**Issue by tkphd** [AdditiveModeling/SolidificationMicrostructure#2]
Hi @Zhyrek,

It's great to see somebody using MMSP out in the wild! I hope your research is going smoothly. I noticed that you're including some of MMSP directly, which certainly simplifies source code management. Unfortunately, it's my duty to point out that MMSP is released under the terms of [GPL v3](https://www.gnu.org/licenses/#GPL), while your include-folder releases it without any terms at all. The basic remedy is to copy [LICENSE](https://github.com/mesoscale/mmsp/blob/develop/LICENSE) from MMSP into your sub-directory `phasefield/include/MMSP`.

in addition, my understanding of [GPL v3 Sec. 5](https://www.gnu.org/licenses/gpl.html#section5) is that, since it propagates portions of MMSP, this work ("SolidificationMicrostructure") is considered a "modified source version" of MMSP and must therefore be distributed with a compatible license, meaning GPL v3 or newer. The basic remedy is to copy [LICENSE](https://github.com/mesoscale/mmsp/blob/develop/LICENSE) from MMSP into your top-level directory.

If the terms of GPL v3 are not acceptable to you, the alternative is to entirely purge the MMSP source code from your repository (including all its history, *e.g.*, using `git filter-branch`), and compile this work with MMSP as an external dependency.

Thanks again for using MMSP, and sorry for the administrative interruption. Carry on.

**Comment by Zhyrek** [comment]
Ah, you're right, that's my bad. I've gone and added licenses to the mentioned areas, including the top level, as I don't see any reason not to make this free software. For the moment I've put the top-level license just under the "phasefield" folder as the folders at the top level are independent from each other. Suppose I'll need to look through this GPL thing more closely.

**Comment by lucentdan** [comment]
Thanks both for nudging this in the correct direction.

**Comment by lucentdan** [comment]
Would really like to see this as a dependency in the future.
